### PR TITLE
Update readme with output files

### PR DESCRIPTION
**Pull request by csadams**
Add reference to JSON and KML outputs. Add list of output URLs.

### CODE REVIEW

**Comment by aanon4** [comment]
While it does output those files, it doesnt output those URLs.

**Comment by csadams** [comment]
Hey, woops, just realized you had replied to this.  
Ok, are you saying that the wording is just wrong, and should instead say "Output files:"?
Or are you saying that this code isn't tied to that domain, and would put out the same files at different URLs, depending what server it's used on?  
Or something else?  
I guess I just wanted an easy place to have the URLs be clickable for quick downloads as we update code, but maybe the github readme page isn't the right spot for that?

**Comment by aanon4** [comment]
> Hey, woops, just realized you had replied to this.
> Ok, are you saying that the wording is just wrong, and should instead say "Output files:"?

This generates files, not URLs. These files need to be put somewhere and that isn't part of this program.

> Or are you saying that this code isn't tied to that domain, and would put out the same files at different URLs, depending what server it's used on?
> Or something else?
> I guess I just wanted an easy place to have the URLs be clickable for quick downloads as we update code, but maybe the github readme page isn't the right spot for that?

I'm not quite sure where that place should be - on the Wiki maybe? This isn't the place for URLs though. I use this code on other meshes (e.g. Southern California) so specific URLs here doesn't make sense.

**Comment by csadams** [comment]
Ok, makes sense... I should have realized that this wasn't just for your one server.  I'll close this request.

**Pull request closed without merging**
